apiVersion: lke.linode.upbound.io/v1alpha1
kind: NodePool
metadata:
  annotations:
    meta.upbound.io/example-id: lke/v1alpha1/nodepool
  labels:
    testing.upbound.io/example-name: my-pool
  name: my-pool
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    nodeCount: 3
    type: g6-standard-2
