apiVersion: objectstorage.linode.upbound.io/v1alpha1
kind: Key
metadata:
  name: test-foo-key
spec:
  forProvider:
    label:  test-foo-key
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: access-foo-key
    namespace: default
